### ISSUE TITLE
Can't enumerate asyncRouter endpoints

### ISSUE THREAD

**Issue by ccope** [AlbertoFdzM/express-list-endpoints#35]
I tried  modifying the getEndpoints function to treat asyncRouter like a router, but that doesn't work (all of the object members appear to be functions). My JS-fu is weak, is there a way to fix this?

**Comment by ccope** [comment]
Yes, that's it

**Comment by AlbertoFdzM** [comment]
I've setup a small test case: https://runkit.com/albertofdzm/5bc37a697b8e2300124ae901

Seems that due to the use of classes and TypeScript the properties being analyzed by `express-list-endpoints` are not accessible by the script being scoped.

I'm afraid that it's not possible to list the endpoints wrapped under this library

**Comment by ccope** [comment]
I patched the asyncRouter module for myself and added the innerRouter.stack as a member of the asyncRouter. Then modifying this module to treat asyncRouter like a router works. I'm not sure if this has performance implications or if there's a better way to redirect access from asyncRouter members to the innerRouter members.

**Comment by AlbertoFdzM** [comment]
Seems to work https://runkit.com/albertofdzm/express-list-endpoints-express-async-router

Closing this issue
